### ISSUE TITLE
Docker up -d時のエラーについて

### ISSUE THREAD

**Issue by gufo777** [PenguinCabinet/yominon#1]
初めまして、ぜひ使わせていただきたく
Raspberry pi zero wにインストールしてます。

Bot Tokenを入力後
Docker up -d を実行すると下記エラーが発生し進行できません
解決方法をご存じであればご教授いただけないでしょうか？

> $ docker-compose up -d
> Building bot
> Sending build context to Docker daemon  84.99kB
> Step 1/21 : FROM ubuntu:18.04
>  ---> ae20adc02307
> Step 2/21 : RUN apt-get update   && apt-get -y install --no-install-recommends     hts-voice-nitech-jp-atr503-m001     open-jtalk     open-jtalk-mecab-naist-jdic     sox     nodejs     ffmpeg
>  ---> [Warning] The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/arm/v6) and no specific platform was requested
>  ---> Running in 4dda983b7127
> The command '/bin/sh -c apt-get update   && apt-get -y install --no-install-recommends     hts-voice-nitech-jp-atr503-m001     open-jtalk     open-jtalk-mecab-naist-jdic     sox     nodejs     ffmpeg' returned a non-zero code: 139
> ERROR: Service 'bot' failed to build : Build failed

**Comment by PenguinCabinet** [comment]
こんにちは、はじめまして
ご興味を持っていただきありがとうございます

ログを見る限り、使用しているベースイメージ(Ubuntu)がARMv7とamd64にのみ対応していたのがエラーの原因だと思います
Raspberry Pi Zero WはARMv6の命令セットを採用していたようでして、私はテストに使用したRaspberry Pi4はARMv8(ARMv7との下位互換あり)でした

READMEに「Yominon can also run on Raspberry Pi.」とあり誤解を招く表現でした、お詫び申し上げます

Raspberry Pi4、Raspberry Pi3、Raspberry Pi2、Raspberry Pi Zero 2 WでYominonは動作すると思います
[Raspberry Piの命令セットの一覧(Wikipedia)](https://ja.wikipedia.org/wiki/Raspberry_Pi#%E4%B8%BB%E3%81%AA%E4%BB%95%E6%A7%98)

よろしくお願いいたします

**Comment by gufo777** [comment]
お返事ありがとうございます！
デバイス問題ですね
ありがとうございました
Pi4入手出来たらまた改めて試してみたいと思います。
